# Generated by Django 2.2.5 on 2019-09-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_file', models.BooleanField(default=False)),
                ('pattern_found', models.BooleanField(default=False)),
                ('pattern', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('filetype', models.CharField(blank=True, max_length=40)),
                ('file_name', models.CharField(blank=True, max_length=100)),
                ('file_link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255)),
            ],
        ),
    ]
